### registration
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Xumoyun",
  "surname": "Eshboyev"
}

### login
POST localhost:8080/auth/login
Content-Type: application/json
Accept-Language: RU

{
  "email": "xumoyunking@gmail.com",
  "password": "251a1a5"
}

### init admin
GET localhost:8080/init/admin